"""Reproducible synthetic byte generators for compression experiments."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
import json
from pathlib import Path
import random
from typing import Any


_PROJECT_ROOT = Path(__file__).resolve().parent.parent
_CONFIG_PATH = _PROJECT_ROOT / "config" / "experiment_config.json"

GENERATOR_NAMES = (
    "random",
    "small_alphabet",
    "repeated_pattern",
    "long_runs",
    "structured",
    "mixed",
)


@dataclass(frozen=True, slots=True)
class GeneratedSample:
    """Generated bytes together with the metadata needed for reproduction."""

    data: bytes
    generator: str
    seed: int
    size: int
    parameters: dict[str, object]


def _load_config() -> dict[str, Any]:
    try:
        with _CONFIG_PATH.open("r", encoding="utf-8") as config_file:
            config = json.load(config_file)
    except FileNotFoundError as exc:
        raise FileNotFoundError(
            f"Experiment configuration file not found: {_CONFIG_PATH}"
        ) from exc

    if not isinstance(config, dict):
        raise TypeError(f"Experiment configuration must be a JSON object: {_CONFIG_PATH}")
    return config


def _required_sample_sizes(config: dict[str, Any]) -> tuple[int, ...]:
    if "sample_sizes" not in config:
        raise KeyError("Missing required experiment config key: sample_sizes")

    values = config["sample_sizes"]
    if not isinstance(values, list) or not values:
        raise TypeError("Experiment config key sample_sizes must be a non-empty list")
    if any(isinstance(value, bool) or not isinstance(value, int) for value in values):
        raise TypeError("Every experiment sample size must be an integer")
    if any(value <= 0 for value in values):
        raise ValueError("Every experiment sample size must be greater than zero")
    if len(values) != len(set(values)):
        raise ValueError("Experiment sample sizes must not contain duplicates")
    return tuple(values)


_CONFIG = _load_config()
SAMPLE_SIZES = _required_sample_sizes(_CONFIG)


def _repeat_to_size(pattern: bytes, size: int) -> bytes:
    repetitions = (size + len(pattern) - 1) // len(pattern)
    return (pattern * repetitions)[:size]


def _generate_random(
    rng: random.Random, size: int
) -> tuple[bytes, dict[str, object]]:
    return rng.randbytes(size), {"distribution": "uniform_bytes"}


def _generate_small_alphabet(
    rng: random.Random, size: int
) -> tuple[bytes, dict[str, object]]:
    alphabet_size = rng.choice((2, 4, 8, 16))
    alphabet = sorted(rng.sample(range(256), alphabet_size))
    data = bytes(rng.choice(alphabet) for _ in range(size))
    parameters: dict[str, object] = {
        "alphabet_size": alphabet_size,
        "alphabet": alphabet,
        "distribution": "uniform",
    }
    return data, parameters


def _generate_repeated_pattern(
    rng: random.Random, size: int
) -> tuple[bytes, dict[str, object]]:
    pattern_length = min(rng.choice((4, 8, 16, 32, 64, 128)), size)
    pattern = rng.randbytes(pattern_length)
    parameters: dict[str, object] = {
        "pattern_length": pattern_length,
        "pattern_hex": pattern.hex(),
    }
    return _repeat_to_size(pattern, size), parameters


def _next_distinct_byte(rng: random.Random, previous: int | None) -> int:
    value = rng.randrange(256)
    while value == previous:
        value = rng.randrange(256)
    return value


def _generate_long_runs(
    rng: random.Random, size: int
) -> tuple[bytes, dict[str, object]]:
    min_run_length, max_run_length = rng.choice(
        ((8, 32), (32, 128), (128, 512), (512, 2048))
    )
    output = bytearray()
    previous_byte: int | None = None

    while len(output) < size:
        value = _next_distinct_byte(rng, previous_byte)
        run_length = rng.randint(min_run_length, max_run_length)
        output.extend(bytes((value,)) * min(run_length, size - len(output)))
        previous_byte = value

    parameters: dict[str, object] = {
        "min_run_length": min_run_length,
        "max_run_length": max_run_length,
        "byte_distribution": "uniform_without_adjacent_run_duplicates",
    }
    return bytes(output), parameters


def _structured_record(
    rng: random.Random, format_name: str, record_index: int
) -> bytes:
    group = rng.randrange(16)
    value = rng.randrange(10_000)
    active = rng.randrange(2)

    if format_name == "jsonl":
        active_text = "true" if active else "false"
        record = (
            f'{{"id":{record_index},"group":{group},'
            f'"active":{active_text},"value":{value}}}\n'
        )
    elif format_name == "csv":
        record = f"{record_index},{group},{active},{value}\n"
    else:
        level = ("INFO", "WARNING", "ERROR")[value % 3]
        record = (
            f"2026-01-{(record_index % 28) + 1:02d} {level} "
            f"group={group} active={active} value={value}\n"
        )
    return record.encode("ascii")


def _generate_structured(
    rng: random.Random, size: int
) -> tuple[bytes, dict[str, object]]:
    format_name = rng.choice(("jsonl", "csv", "log"))
    output = bytearray()
    if format_name == "csv":
        output.extend(b"id,group,active,value\n")

    record_index = 0
    while len(output) < size:
        output.extend(_structured_record(rng, format_name, record_index))
        record_index += 1

    parameters: dict[str, object] = {
        "format": format_name,
        "group_count": 16,
        "value_range": [0, 9_999],
    }
    return bytes(output[:size]), parameters


_BASE_GENERATORS: dict[
    str, Callable[[random.Random, int], tuple[bytes, dict[str, object]]]
] = {
    "random": _generate_random,
    "small_alphabet": _generate_small_alphabet,
    "repeated_pattern": _generate_repeated_pattern,
    "long_runs": _generate_long_runs,
    "structured": _generate_structured,
}


def _generate_mixed(
    rng: random.Random, size: int
) -> tuple[bytes, dict[str, object]]:
    segment_count = min(len(_BASE_GENERATORS), size)
    generator_names = list(_BASE_GENERATORS)
    rng.shuffle(generator_names)
    generator_names = generator_names[:segment_count]

    base_segment_size, remainder = divmod(size, segment_count)
    segment_sizes = [
        base_segment_size + (1 if index < remainder else 0)
        for index in range(segment_count)
    ]

    segments = []
    segment_metadata = []
    for generator_name, segment_size in zip(generator_names, segment_sizes):
        segment, parameters = _BASE_GENERATORS[generator_name](rng, segment_size)
        segments.append(segment)
        segment_metadata.append(
            {
                "generator": generator_name,
                "size": segment_size,
                "parameters": parameters,
            }
        )

    return b"".join(segments), {"segments": segment_metadata}


def generate_sample(generator: str, size: int, seed: int) -> GeneratedSample:
    """Generate one exact-size sample deterministically from its recorded inputs."""
    if generator not in GENERATOR_NAMES:
        supported = ", ".join(GENERATOR_NAMES)
        raise ValueError(f"Unsupported generator: {generator!r}. Supported: {supported}")
    if isinstance(size, bool) or not isinstance(size, int):
        raise TypeError("Sample size must be an integer")
    if size <= 0:
        raise ValueError("Sample size must be greater than zero")
    if isinstance(seed, bool) or not isinstance(seed, int):
        raise TypeError("Random seed must be an integer")

    rng = random.Random(seed)
    if generator == "mixed":
        data, parameters = _generate_mixed(rng, size)
    else:
        data, parameters = _BASE_GENERATORS[generator](rng, size)

    if len(data) != size:
        raise RuntimeError(
            f"Generator {generator!r} returned {len(data)} bytes; expected {size}"
        )
    return GeneratedSample(
        data=data,
        generator=generator,
        seed=seed,
        size=size,
        parameters=parameters,
    )
